apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: development

resources:
  - ../../base
  - namespaces.yaml

patches:
  - path: patch-replicas.yaml
  - path: patch-configmap.yaml