apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  ports:
    - port: 3000            # Puerto del servicio dentro del clúster
      targetPort: 3000      # Puerto del contenedor
      nodePort: 31000       # Puerto expuesto externamente (opcional si es NodePort)
  type: NodePort            # Puede ser NodePort, ClusterIP o LoadBalancer según tu necesidad
