apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jouncato/product-service-kustomize.git
    targetRevision: HEAD
    path: overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m