apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: qa-
namespace: qa

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: patch-replicas.yaml
  - path: patch-configmap.yaml
  - path: patch-service.yaml