apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  ports:
    - name: http-prod          
      port: 3000          
      targetPort: 3000     
      nodePort: 56300      
  type: NodePort
